import Footer from "@/components/Footer/Footer";
import MobileFooter from "@/components/Footer/MobileFooter";
import Header from "@/components/Header/Header";
import MobileHeader from "@/components/Header/MobileHeader";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full flex justify-center">
      <body className="flex flex-col width-full items-center">
        <div className="sticky top-0 w-full z-20 w-[100vw]">
          <div className="mobile:hidden tablet:flex w-full flex justify-center bg-white">
            <Header />
          </div>
          <div className="tablet:hidden">
            <MobileHeader />
          </div>
        </div>
        <div className="bg-[#F6F7F9] w-[100vw] flex justify-center">
          <div className="max-w-[1312px] w-full">{children}</div>
        </div>
        <div className="mobile:hidden tablet:flex w-[100vw] bg-white flex justify-center">
          <div className="max-w-[1440px] w-full">
            <Footer />
          </div>
        </div>
        <div className="mobile:block tablet:hidden bg-[#F6F7F9]">
          <MobileFooter />
        </div>
      </body>
    </html>
  );
}
