import Header from "@/components/Header/Header";
import MobileHeader from "@/components/Header/MobileHeader";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="sticky top-0 w-full">
          <div className="mobile:hidden tablet:block">
            <Header />
          </div>
          <div className="tablet:hidden">
            <MobileHeader />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
